python ./get_review.py --file_name bottom_leggings
python ./get_review.py --file_name bottom_denim
python ./get_review.py --file_name bottom_cotton
python ./get_review.py --file_name bottom_slacks
python ./get_review.py --file_name bottom_jogger
python ./get_review.py --file_name bottom_jumpper
python ./get_review.py --file_name bottom_short
python ./get_review.py --file_name bottom_etc
python ./get_review.py --file_name top_short
python ./get_review.py --file_name top_sweatshirt
python ./get_review.py --file_name top_knit
python ./get_review.py --file_name top_hood
python ./get_review.py --file_name top_long
python ./get_review.py --file_name top_shirts
python ./get_review.py --file_name top_polo
python ./get_review.py --file_name top_sleeveless